version: "2"
services:
  nginx: 
    build: ./nginx
    links:
        - web:web
    ports:
      - "3000:80"
  web:
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"